repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.100.0"
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
      - id: terraform_validate
        args:
          - --tf-init-args=-upgrade
          - --hook-config=--retry-once-with-cleanup=true
      - id: terraform_trivy
        args:
          - --args=--ignorefile=__GIT_WORKING_DIR__/.trivyignore
          - --args=--tf-exclude-downloaded-modules
          - --args=--skip-dirs="**/.terraform"
  - repo: https://github.com/gitleaks/gitleaks
    rev: "v8.24.0"
    hooks:
      - id: gitleaks
